Added Go Fuzzing on Sample API which is integrated with Keploy
keploy/samples-go pull request #49
Opened 2023-03-30 03:21 UTC by kartikvirendrar

2023-04-12 09:34 UTC, PranshuSrivastava requested changes

2023-04-12 09:34 UTC, PranshuSrivastava commented on go-fuzzing/main.go
> +		}
@kartikvirendrar Creating an infinite for loop is not the correct way of implementing go fuzzing. You need to follow a specific algorithm to implement it. Kindly checkout the [official docs](https://go.dev/security/fuzz/) and implement the function according to that.

2023-04-22 05:00 UTC, kartikvirendrar commented on go-fuzzing/main.go
> +		}
ok, will update the code

2023-05-02 04:37 UTC, PranshuSrivastava commented
@kartikvirendrar This implementation is still wrong. For implementing fuzzing you need to create test files which will have fuzz tests to implement the fuzzing. Using a for loop is not the correct approach for fuzzing. I recommend you to take a look at the [official docs](https://go.dev/security/fuzz/) again.

2023-05-25 02:42 UTC, closed without merging